- README.md
Update README.md with latest accurate info
> Update README.md with latest accurate info

- README.md
Adding ToyCar sample description in README.md
> chore: Adding ToyCar sample description

- UI/UnoContoso/UnoContoso.Droid/UnoContoso.Droid.csproj
- UI/UnoContoso/UnoContoso.Shared/ViewModels/CustomerListViewModel.cs
- UI/UnoContoso/UnoContoso.Shared/ViewModels/OrderListViewModel.cs
- UI/UnoContoso/UnoContoso.Shared/Views/CustomerDetailView.xaml
- UI/UnoContoso/UnoContoso.Shared/Views/CustomerListView.xaml
- UI/UnoContoso/UnoContoso.Shared/Views/OrderListView.xaml
- UI/UnoContoso/UnoContoso.UWP/UnoContoso.Uwp.csproj
- UI/UnoContoso/UnoContoso.Wasm/LinkerConfig.xml
- UI/UnoContoso/UnoContoso.Wasm/UnoContoso.Wasm.csproj
- UI/UnoContoso/UnoContoso.iOS/UnoContoso.iOS.csproj
- UI/UnoContoso/UnoContoso.macOS/UnoContoso.macOS.csproj
- UI/UnoContoso/UnoContoso.sln
Modified DataTemplate, and code refactored.
> Edit DataTemplate, Code refactoring

- UI/MapControlSample/MapControlSample/MapControlSample.Droid/MapControlSample.Droid.csproj
- UI/MapControlSample/MapControlSample/MapControlSample.Droid/Properties/AssemblyInfo.cs
- UI/MapControlSample/MapControlSample/MapControlSample.Shared/App.xaml
- UI/MapControlSample/MapControlSample/MapControlSample.Shared/MainPage.xaml
- UI/MapControlSample/MapControlSample/MapControlSample.Shared/MainPage.xaml.cs
- UI/MapControlSample/MapControlSample/MapControlSample.UWP/MapControlSample.UWP.csproj
- UI/MapControlSample/MapControlSample/MapControlSample.Wasm/MapControlSample.Wasm.csproj
- UI/MapControlSample/MapControlSample/MapControlSample.iOS/MapControlSample.iOS.csproj
- UI/MapControlSample/MapControlSample/README.md
The MapControl now displays again.
> Update MapControl sample for Uno 3 changes and add README

- UI/StatusBarThemeColor/StatusBarColorSample.Shared/App.xaml.cs
ported change from code review here: https://github.com/unoplatform/uno/pull/5438#discussion_r594330573
> refac(StatusBarColorSample): code review suggestion

- README.md
Changed to match 'about uno' from Uno github page
> docs: update readme uno samples

- .vsts-ci.canaries.yml
- .vsts-ci.yml
- UI/AndroidCustomCamera/AndroidCustomCamera/AndroidCustomCamera.Droid/AndroidCustomCamera.Droid.csproj
- UI/AndroidCustomCamera/AndroidCustomCamera/AndroidCustomCamera.Droid/Properties/AndroidManifest.xml
- UI/AndroidCustomCamera/AndroidCustomCamera/AndroidCustomCamera.Shared/App.xaml
- UI/AndroidCustomCamera/AndroidCustomCamera/AndroidCustomCamera.Shared/App.xaml.cs
AndroidCustomCamera upgraded to Uno 4.1.9
> 8404 - AndroidCustomCamera

- UI/Benchmark/AppBenchmark/AppBenchmark.Droid/AppBenchmark.Droid.csproj
- UI/Benchmark/AppBenchmark/AppBenchmark.Droid/Properties/AndroidManifest.xml
- UI/Benchmark/AppBenchmark/AppBenchmark.Shared/App.xaml
- UI/Benchmark/AppBenchmark/AppBenchmark.Shared/App.xaml.cs
- UI/Benchmark/AppBenchmark/AppBenchmark.UWP/AppBenchmark.UWP.csproj
- UI/Benchmark/AppBenchmark/AppBenchmark.Wasm/AppBenchmark.Wasm.csproj
- UI/Benchmark/AppBenchmark/AppBenchmark.Wasm/LinkerConfig.xml
- UI/Benchmark/AppBenchmark/AppBenchmark.iOS/AppBenchmark.iOS.csproj
AppBenchmark upgraded to Uno 4.1.9
> chore: Benchmark Uno 4.1.9

- UI/PackageResources/PackageResourcesSample/PackageResourcesSample.Droid/PackageResourcesSample.Droid.csproj
- UI/PackageResources/PackageResourcesSample/PackageResourcesSample.Droid/Properties/AndroidManifest.xml
- UI/PackageResources/PackageResourcesSample/PackageResourcesSample.Shared/App.xaml.cs
- UI/PackageResources/PackageResourcesSample/PackageResourcesSample.Skia.Gtk/PackageResourcesSample.Skia.Gtk.csproj
- UI/PackageResources/PackageResourcesSample/PackageResourcesSample.Skia.Tizen/PackageResourcesSample.Skia.Tizen.csproj
- UI/PackageResources/PackageResourcesSample/PackageResourcesSample.Skia.Wpf.Host/PackageResourcesSample.Skia.Wpf.Host.csproj
- UI/PackageResources/PackageResourcesSample/PackageResourcesSample.Skia.Wpf/PackageResourcesSample.Skia.Wpf.csproj
- UI/PackageResources/PackageResourcesSample/PackageResourcesSample.UWP/PackageResourcesSample.UWP.csproj
- UI/PackageResources/PackageResourcesSample/PackageResourcesSample.Wasm/LinkerConfig.xml
- UI/PackageResources/PackageResourcesSample/PackageResourcesSample.Wasm/PackageResourcesSample.Wasm.csproj
- UI/PackageResources/PackageResourcesSample/PackageResourcesSample.iOS/PackageResourcesSample.iOS.csproj
- UI/PackageResources/PackageResourcesSample/PackageResourcesSample.macOS/PackageResourcesSample.macOS.csproj
PackageResources updated to Uno 4.1.9
> chore: PackageResources Uno 4.1.9

- UI/NativeFrameNav/NativeFrameNav.Droid/NativeFrameNav.Droid.csproj
- UI/NativeFrameNav/NativeFrameNav.Droid/Properties/AndroidManifest.xml
- UI/NativeFrameNav/NativeFrameNav.Shared/App.xaml.cs
- UI/NativeFrameNav/NativeFrameNav.Shared/MainPage.xaml
- UI/NativeFrameNav/NativeFrameNav.Skia.Gtk/NativeFrameNav.Skia.Gtk.csproj
- UI/NativeFrameNav/NativeFrameNav.Skia.Tizen/NativeFrameNav.Skia.Tizen.csproj
- UI/NativeFrameNav/NativeFrameNav.Skia.WPF.Host/NativeFrameNav.Skia.Wpf.Host.csproj
- UI/NativeFrameNav/NativeFrameNav.Skia.WPF/NativeFrameNav.Skia.WPF.csproj
- UI/NativeFrameNav/NativeFrameNav.UWP/NativeFrameNav.Uwp.csproj
- UI/NativeFrameNav/NativeFrameNav.Wasm/NativeFrameNav.Wasm.csproj
- UI/NativeFrameNav/NativeFrameNav.iOS/NativeFrameNav.iOS.csproj
- UI/NativeFrameNav/NativeFrameNav.macOS/NativeFrameNav.macOS.csproj
- UI/NativeFrameNav/NativeFrameNav.sln
NativeFrameNav updated to Uno 4.1.9
> chore: NativeFrameNav Uno 4.1.9

- UI/LocalizationSamples/Localization/UnoLocalization.Droid/Properties/AndroidManifest.xml
- UI/LocalizationSamples/Localization/UnoLocalization.Droid/UnoLocalization.Droid.csproj
- UI/LocalizationSamples/Localization/UnoLocalization.Shared/App.xaml
- UI/LocalizationSamples/Localization/UnoLocalization.Shared/App.xaml.cs
- UI/LocalizationSamples/Localization/UnoLocalization.Shared/MainPage.xaml
- UI/LocalizationSamples/Localization/UnoLocalization.Skia.Gtk/UnoLocalization.Skia.Gtk.csproj
- UI/LocalizationSamples/Localization/UnoLocalization.Skia.Tizen/UnoLocalization.Skia.Tizen.csproj
- UI/LocalizationSamples/Localization/UnoLocalization.Skia.WPF.Host/UnoLocalization.Skia.Wpf.Host.csproj
- UI/LocalizationSamples/Localization/UnoLocalization.Skia.WPF/UnoLocalization.Skia.WPF.csproj
- UI/LocalizationSamples/Localization/UnoLocalization.UWP/UnoLocalization.Uwp.csproj
- UI/LocalizationSamples/Localization/UnoLocalization.Wasm/LinkerConfig.xml
- UI/LocalizationSamples/Localization/UnoLocalization.Wasm/UnoLocalization.Wasm.csproj
- UI/LocalizationSamples/Localization/UnoLocalization.iOS/UnoLocalization.iOS.csproj
- UI/LocalizationSamples/Localization/UnoLocalization.macOS/UnoLocalization.macOS.csproj
- UI/LocalizationSamples/Localization/UnoLocalization.sln
- UI/LocalizationSamples/RuntimeCultureSwitching/UnoLocalization.Droid/Properties/AndroidManifest.xml
- UI/LocalizationSamples/RuntimeCultureSwitching/UnoLocalization.Droid/UnoLocalization.Droid.csproj
- UI/LocalizationSamples/RuntimeCultureSwitching/UnoLocalization.Shared/App.xaml.cs
- UI/LocalizationSamples/RuntimeCultureSwitching/UnoLocalization.Shared/LanguageSettings.xaml
- UI/LocalizationSamples/RuntimeCultureSwitching/UnoLocalization.Shared/MainPage.xaml
- UI/LocalizationSamples/RuntimeCultureSwitching/UnoLocalization.Shared/Page1.xaml
- UI/LocalizationSamples/RuntimeCultureSwitching/UnoLocalization.Skia.Gtk/UnoLocalization.Skia.Gtk.csproj
- UI/LocalizationSamples/RuntimeCultureSwitching/UnoLocalization.Skia.Tizen/UnoLocalization.Skia.Tizen.csproj
- UI/LocalizationSamples/RuntimeCultureSwitching/UnoLocalization.Skia.WPF.Host/UnoLocalization.Skia.Wpf.Host.csproj
- UI/LocalizationSamples/RuntimeCultureSwitching/UnoLocalization.Skia.WPF/UnoLocalization.Skia.WPF.csproj
- UI/LocalizationSamples/RuntimeCultureSwitching/UnoLocalization.UWP/UnoLocalization.Uwp.csproj
- UI/LocalizationSamples/RuntimeCultureSwitching/UnoLocalization.Wasm/LinkerConfig.xml
- UI/LocalizationSamples/RuntimeCultureSwitching/UnoLocalization.Wasm/UnoLocalization.Wasm.csproj
- UI/LocalizationSamples/RuntimeCultureSwitching/UnoLocalization.iOS/UnoLocalization.iOS.csproj
- UI/LocalizationSamples/RuntimeCultureSwitching/UnoLocalization.macOS/UnoLocalization.macOS.csproj
LocalizationSamples updated to Uno 4.1.9
Added background to page, as when it was showing a white screen with white foreground. Probably because i'm using dark scheme here. 
It happens only on skia and wasm.
> chore: LocalizationSamples Uno 4.1.9

- UI/SplashScreenSample/SplashScreenSample.Droid/Properties/AndroidManifest.xml
- UI/SplashScreenSample/SplashScreenSample.Droid/SplashScreenSample.Droid.csproj
- UI/SplashScreenSample/SplashScreenSample.Shared/App.xaml
- UI/SplashScreenSample/SplashScreenSample.Shared/App.xaml.cs
- UI/SplashScreenSample/SplashScreenSample.Skia.Gtk/SplashScreenSample.Skia.Gtk.csproj
- UI/SplashScreenSample/SplashScreenSample.Skia.Tizen/SplashScreenSample.Skia.Tizen.csproj
- UI/SplashScreenSample/SplashScreenSample.Skia.WPF.Host/SplashScreenSample.Skia.Wpf.Host.csproj
- UI/SplashScreenSample/SplashScreenSample.Skia.WPF/SplashScreenSample.Skia.WPF.csproj
- UI/SplashScreenSample/SplashScreenSample.UWP/SplashScreenSample.Uwp.csproj
- UI/SplashScreenSample/SplashScreenSample.Wasm/LinkerConfig.xml
- UI/SplashScreenSample/SplashScreenSample.Wasm/SplashScreenSample.Wasm.csproj
- UI/SplashScreenSample/SplashScreenSample.iOS/SplashScreenSample.iOS.csproj
- UI/SplashScreenSample/SplashScreenSample.macOS/SplashScreenSample.macOS.csproj
SplashScreenSample updated to Uno 4.1.9
> chore: SplashScreenSample Uno 4.1.9

- UI/StatusBarThemeColor/StatusBarColorSample.Droid/Properties/AndroidManifest.xml
- UI/StatusBarThemeColor/StatusBarColorSample.Droid/StatusBarColorSample.Droid.csproj
- UI/StatusBarThemeColor/StatusBarColorSample.Shared/App.xaml
- UI/StatusBarThemeColor/StatusBarColorSample.Shared/App.xaml.cs
- UI/StatusBarThemeColor/StatusBarColorSample.UWP/StatusBarColorSample.Uwp.csproj
- UI/StatusBarThemeColor/StatusBarColorSample.Wasm/LinkerConfig.xml
- UI/StatusBarThemeColor/StatusBarColorSample.Wasm/Properties/launchSettings.json
- UI/StatusBarThemeColor/StatusBarColorSample.Wasm/StatusBarColorSample.Wasm.csproj
- UI/StatusBarThemeColor/StatusBarColorSample.iOS/StatusBarColorSample.iOS.csproj
- UI/StatusBarThemeColor/StatusBarColorSample.macOS/StatusBarColorSample.macOS.csproj
StatusBarThemeColor updated to Uno 4.1.9
> chore: StatusBarThemeColor Uno 4.1.9

- UI/FileSavePickeriOS/FileSavePickeriOS/FileSavePickeriOS.Shared/App.xaml.cs
- UI/FileSavePickeriOS/FileSavePickeriOS/FileSavePickeriOS.iOS/FileSavePickeriOS.iOS.csproj
FileSavePickeriOS updated to Uno 4.1.9
> chore: FileSavePickeriOS Uno 4.1.9

- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Droid/EmbeddedResourcesSample.Droid.csproj
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Droid/Properties/AndroidManifest.xml
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Shared/App.xaml
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Shared/App.xaml.cs
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Skia.Gtk/EmbeddedResourcesSample.Skia.Gtk.csproj
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Skia.Tizen/EmbeddedResourcesSample.Skia.Tizen.csproj
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Skia.Wpf.Host/EmbeddedResourcesSample.Skia.Wpf.Host.csproj
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Skia.Wpf/EmbeddedResourcesSample.Skia.Wpf.csproj
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.UWP/EmbeddedResourcesSample.UWP.csproj
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Wasm/EmbeddedResourcesSample.Wasm.csproj
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Wasm/LinkerConfig.xml
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.iOS/EmbeddedResourcesSample.iOS.csproj
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.macOS/EmbeddedResourcesSample.macOS.csproj
EmbeddedResourcesSample updated to Uno 4.1.9
> chore: EmbeddedResourcesSample Uno 4.1.9

- UI/DualScreenSample/DualScreenSample.Droid/DualScreenSample.Droid.csproj
- UI/DualScreenSample/DualScreenSample.Droid/Properties/AndroidManifest.xml
- UI/DualScreenSample/DualScreenSample.Shared/App.xaml
- UI/DualScreenSample/DualScreenSample.Shared/App.xaml.cs
- UI/DualScreenSample/DualScreenSample.UWP/DualScreenSample.UWP.csproj
- UI/DualScreenSample/DualScreenSample.Wasm/DualScreenSample.Wasm.csproj
- UI/DualScreenSample/DualScreenSample.Wasm/LinkerConfig.xml
- UI/DualScreenSample/DualScreenSample.iOS/DualScreenSample.iOS.csproj
- UI/DualScreenSample/DualScreenSample.macOS/DualScreenSample.macOS.csproj
- UI/DualScreenSample/DualScreenSample.sln
DualScreenSample updated to Uno 4.1.9
> chore: DualScreenSample Uno 4.1.9

- UI/UnoEthereumBlockChain/DemoApp/DemoApp/DemoApp.Droid/DemoApp.Droid.csproj
- UI/UnoEthereumBlockChain/DemoApp/DemoApp/DemoApp.Droid/Properties/AndroidManifest.xml
- UI/UnoEthereumBlockChain/DemoApp/DemoApp/DemoApp.Shared/App.xaml.cs
- UI/UnoEthereumBlockChain/DemoApp/DemoApp/DemoApp.Skia.Gtk/DemoApp.Skia.Gtk.csproj
- UI/UnoEthereumBlockChain/DemoApp/DemoApp/DemoApp.Skia.Tizen/DemoApp.Skia.Tizen.csproj
- UI/UnoEthereumBlockChain/DemoApp/DemoApp/DemoApp.Skia.Wpf.Host/DemoApp.Skia.Wpf.Host.csproj
- UI/UnoEthereumBlockChain/DemoApp/DemoApp/DemoApp.Skia.Wpf/DemoApp.Skia.Wpf.csproj
- UI/UnoEthereumBlockChain/DemoApp/DemoApp/DemoApp.UWP/DemoApp.UWP.csproj
- UI/UnoEthereumBlockChain/DemoApp/DemoApp/DemoApp.Wasm/DemoApp.Wasm.csproj
- UI/UnoEthereumBlockChain/DemoApp/DemoApp/DemoApp.iOS/DemoApp.iOS.csproj
- UI/UnoEthereumBlockChain/DemoApp/DemoApp/DemoApp.macOS/DemoApp.macOS.csproj
- UI/UnoEthereumBlockChain/UnoPharmaSupply/UnoPharmaSupply/UnoPharmaSupply.csproj
EthereumBlockChain updated to Uno 4.1.9
> chore: EthereumBlockChain Uno 4.1.9

- UI/WCTDataTreeTabSample/WCTDataTreeTabSample/WCTDataTreeTabSample.Droid/Properties/AndroidManifest.xml
- UI/WCTDataTreeTabSample/WCTDataTreeTabSample/WCTDataTreeTabSample.Droid/WCTDataTreeTabSample.Droid.csproj
- UI/WCTDataTreeTabSample/WCTDataTreeTabSample/WCTDataTreeTabSample.Shared/App.xaml.cs
- UI/WCTDataTreeTabSample/WCTDataTreeTabSample/WCTDataTreeTabSample.Skia.Gtk/WCTDataTreeTabSample.Skia.Gtk.csproj
- UI/WCTDataTreeTabSample/WCTDataTreeTabSample/WCTDataTreeTabSample.Skia.Tizen/WCTDataTreeTabSample.Skia.Tizen.csproj
- UI/WCTDataTreeTabSample/WCTDataTreeTabSample/WCTDataTreeTabSample.Skia.Wpf.Host/WCTDataTreeTabSample.Skia.Wpf.Host.csproj
- UI/WCTDataTreeTabSample/WCTDataTreeTabSample/WCTDataTreeTabSample.Skia.Wpf/WCTDataTreeTabSample.Skia.Wpf.csproj
- UI/WCTDataTreeTabSample/WCTDataTreeTabSample/WCTDataTreeTabSample.UWP/WCTDataTreeTabSample.UWP.csproj
- UI/WCTDataTreeTabSample/WCTDataTreeTabSample/WCTDataTreeTabSample.Wasm/LinkerConfig.xml
- UI/WCTDataTreeTabSample/WCTDataTreeTabSample/WCTDataTreeTabSample.Wasm/WCTDataTreeTabSample.Wasm.csproj
- UI/WCTDataTreeTabSample/WCTDataTreeTabSample/WCTDataTreeTabSample.iOS/WCTDataTreeTabSample.iOS.csproj
- UI/WCTDataTreeTabSample/WCTDataTreeTabSample/WCTDataTreeTabSample.macOS/WCTDataTreeTabSample.macOS.csproj
WCTDataTreeTabSample updated to Uno 4.1.9
> chore: WCTDataTreeTabSample Uno 4.1.9

- UI/UnoCupertinoSample/UnoCupertinoSample.Droid/Properties/AndroidManifest.xml
- UI/UnoCupertinoSample/UnoCupertinoSample.Droid/UnoCupertinoSample.Droid.csproj
- UI/UnoCupertinoSample/UnoCupertinoSample.Shared/App.xaml.cs
- UI/UnoCupertinoSample/UnoCupertinoSample.Shared/MainPage.xaml
- UI/UnoCupertinoSample/UnoCupertinoSample.Skia.Gtk/UnoCupertinoSample.Skia.Gtk.csproj
- UI/UnoCupertinoSample/UnoCupertinoSample.Skia.Tizen/UnoCupertinoSample.Skia.Tizen.csproj
- UI/UnoCupertinoSample/UnoCupertinoSample.Skia.Wpf.Host/UnoCupertinoSample.Skia.Wpf.Host.csproj
- UI/UnoCupertinoSample/UnoCupertinoSample.Skia.Wpf/UnoCupertinoSample.Skia.Wpf.csproj
- UI/UnoCupertinoSample/UnoCupertinoSample.UWP/UnoCupertinoSample.UWP.csproj
- UI/UnoCupertinoSample/UnoCupertinoSample.Wasm/UnoCupertinoSample.Wasm.csproj
- UI/UnoCupertinoSample/UnoCupertinoSample.iOS/UnoCupertinoSample.iOS.csproj
- UI/UnoCupertinoSample/UnoCupertinoSample.macOS/UnoCupertinoSample.macOS.csproj
UnoCupertinoSample updated to Uno 4.1.9
> chore: UnoCupertinoSample Uno 4.1.9

- UI/XamlBasics/ListViewSample/ListViewSample.Mobile/ListViewSample.Mobile.csproj
- UI/XamlBasics/ListViewSample/ListViewSample.Skia.Gtk/ListViewSample.Skia.Gtk.csproj
- UI/XamlBasics/ListViewSample/ListViewSample.Skia.Wpf.Host/ListViewSample.Skia.Wpf.Host.csproj
- UI/XamlBasics/ListViewSample/ListViewSample.Skia.Wpf/ListViewSample.Skia.Wpf.csproj
- UI/XamlBasics/ListViewSample/ListViewSample.UWP/ListViewSample.UWP.csproj
- UI/XamlBasics/ListViewSample/ListViewSample.Wasm/ListViewSample.Wasm.csproj
It uses Net 6. Not listed on Readme
So, WASM, SKIA and UWP worked fine.
Couldn't test: Mobile.
> chore: XamlBasics Uno 4.1.9

- UI/TimeEntry/TimeEntryUno/TimeEntryUno.Shared/App.xaml.cs
- UI/TimeEntry/TimeEntryUno/TimeEntryUno.Shared/WebServices/WebApiBase.cs
- UI/TimeEntry/TimeEntryUno/TimeEntryUno.UWP/TimeEntryUno.Uwp.csproj
- UI/TimeEntry/TimeEntryUno/TimeEntryUno.Wasm/LinkerConfig.xml
- UI/TimeEntry/TimeEntryUno/TimeEntryUno.Wasm/TimeEntryUno.Wasm.csproj
TimeEntry updated to Uno 4.1.9
> chore: TimeEntry Uno 4.1.9

- UI/Authentication.OidcDemo/Authentication.OidcDemo.sln
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.Droid/Authentication.OidcDemo.Droid.csproj
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.Droid/MainActivity.cs
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.Droid/Properties/AndroidManifest.xml
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.Droid/WebAuthenticationBrokerActivity.cs
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.Shared/App.xaml
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.Shared/App.xaml.cs
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.Shared/MainPage.xaml.cs
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.Skia.Gtk/Authentication.OidcDemo.Skia.Gtk.csproj
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.Skia.Tizen/Authentication.OidcDemo.Skia.Tizen.csproj
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.Skia.Wpf.Host/Authentication.OidcDemo.Skia.Wpf.Host.csproj
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.Skia.Wpf/Authentication.OidcDemo.Skia.Wpf.csproj
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.UWP/Authentication.OidcDemo.UWP.csproj
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.Wasm/Authentication.OidcDemo.Wasm.csproj
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.Wasm/LinkerConfig.xml
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.iOS/Authentication.OidcDemo.iOS.csproj
- UI/Authentication.OidcDemo/Authentication.OidcDemo/Authentication.OidcDemo.macOS/Authentication.OidcDemo.macOS.csproj
Authentication.OidcDemo updated to Uno 4.1.9
Still getting a blank screen on WASM. No specific error found. 
Working on all platforms (skia doesn't have support, as expected).
Issue created: [https://github.com/unoplatform/Uno.Samples/issues/122](https://github.com/unoplatform/Uno.Samples/issues/122)
> chore: Authentication.OidcDemo Uno 4.1.9

- UI/ChatSignalR/UnoChat.Client/UnoChat.Client.Droid/Properties/AndroidManifest.xml
- UI/ChatSignalR/UnoChat.Client/UnoChat.Client.Droid/UnoChat.Client.Droid.csproj
- UI/ChatSignalR/UnoChat.Client/UnoChat.Client.Shared/App.xaml.cs
- UI/ChatSignalR/UnoChat.Client/UnoChat.Client.UWP/UnoChat.Client.UWP.csproj
- UI/ChatSignalR/UnoChat.Client/UnoChat.Client.Wasm/UnoChat.Client.Wasm.csproj
- UI/ChatSignalR/UnoChat.Client/UnoChat.Client.iOS/UnoChat.Client.iOS.csproj
- UI/ChatSignalR/UnoChat.Client/UnoChat.Client.macOS/UnoChat.Client.macOS.csproj
- UI/ChatSignalR/UnoChat.sln
ChatSignalR updated to Uno 4.1.9
Attention: WASM client can't connect to the service server.
All other platforms work fine. 
New Issue: 
[https://github.com/unoplatform/Uno.Samples/issues/118](https://github.com/unoplatform/Uno.Samples/issues/118)
> chore: ChatSignalR Uno 4.1.9

- UI/UnoMaterialSample/UnoMaterialSample.Droid/Properties/AndroidManifest.xml
- UI/UnoMaterialSample/UnoMaterialSample.Droid/UnoMaterialSample.Droid.csproj
- UI/UnoMaterialSample/UnoMaterialSample.Shared/App.xaml
- UI/UnoMaterialSample/UnoMaterialSample.Shared/App.xaml.cs
- UI/UnoMaterialSample/UnoMaterialSample.Shared/MainPage.xaml
- UI/UnoMaterialSample/UnoMaterialSample.Skia.Gtk/UnoMaterialSample.Skia.Gtk.csproj
- UI/UnoMaterialSample/UnoMaterialSample.Skia.Tizen/UnoMaterialSample.Skia.Tizen.csproj
- UI/UnoMaterialSample/UnoMaterialSample.Skia.WPF.Host/UnoMaterialSample.Skia.Wpf.Host.csproj
- UI/UnoMaterialSample/UnoMaterialSample.Skia.WPF/UnoMaterialSample.Skia.WPF.csproj
- UI/UnoMaterialSample/UnoMaterialSample.UWP/UnoMaterialSample.Uwp.csproj
- UI/UnoMaterialSample/UnoMaterialSample.Wasm/LinkerConfig.xml
- UI/UnoMaterialSample/UnoMaterialSample.Wasm/UnoMaterialSample.Wasm.csproj
- UI/UnoMaterialSample/UnoMaterialSample.iOS/UnoMaterialSample.iOS.csproj
- UI/UnoMaterialSample/UnoMaterialSample.macOS/UnoMaterialSample.macOS.csproj
- UI/UnoMaterialSample/UnoMaterialSample.sln
UnoMaterialSample updated to Uno 4.1.9
> chore: UnoMaterialSample Uno 4.1.9

- reference/SimpleCalculator/Extensions.props
- reference/SimpleCalculator/SimpleCalculator.UI/App.xaml.cs
- reference/SimpleCalculator/SimpleCalculator.UI/App.xaml.host.cs
- reference/SimpleCalculator/SimpleCalculator.UI/Views/CalculatorMarkupView.cs
- reference/SimpleCalculator/SimpleCalculator.Windows/SimpleCalculator.Windows.csproj
Note: We have to replace the AutoLKayout by grid before merging this
> chore: Update to latests extensions

- .vsts-ci.canaries.yml
- .vsts-ci.yml
fixes https://github.com/unoplatform/Uno.Samples/issues/208
> Misc canary adjustments

- README.md
#190 
Updating docs to include all samples
> feat: Adding missing samples

- reference/Commerce/Commerce.UI/App.xaml.cs
- reference/Commerce/Commerce.UI/App.xaml.host.cs
- reference/Commerce/Commerce.Wasm/Commerce.Wasm.csproj
- Fix for canary build for wasm
- Fix for startup logic
> fix: Correcting Commerce sample

- UI/MvuxHowTos/SliderApp/SliderApp/MainPage.xaml
- UI/MvuxHowTos/SliderApp/SliderApp/SliderModel.cs
This is a minor addition to the SliderApp, it adds usage of a Command to interact with the Model.
> fix: Added Command to MVUX SliderApp

- README.md
- reference/Commerce/Commerce/Directory.Build.props
#416 
Update description so that it includes what features are being used.
> fix: commerce app description

- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Mobile/EmbeddedResourcesSample.Mobile.csproj
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Shared/MainPage.xaml
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Skia.Gtk/EmbeddedResourcesSample.Skia.Gtk.csproj
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Skia.Wpf/EmbeddedResourcesSample.Skia.Wpf.csproj
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Wasm/EmbeddedResourcesSample.Wasm.csproj
- UI/EmbeddedResources/EmbeddedResourcesSample/EmbeddedResourcesSample.Windows/EmbeddedResourcesSample.Windows.csproj
> feat: add safe area to EmbeddedResourcesSample

- README.md
- UI/InsertingSeparators/InsertingSeparators.Mobile/InsertingSeparators.Mobile.csproj
- UI/InsertingSeparators/InsertingSeparators.Shared/MainPage.xaml
- UI/InsertingSeparators/InsertingSeparators.Skia.Gtk/InsertingSeparators.Skia.Gtk.csproj
- UI/InsertingSeparators/InsertingSeparators.Wasm/InsertingSeparators.Wasm.csproj
- UI/InsertingSeparators/InsertingSeparators.Windows/InsertingSeparators.Windows.csproj
> Added Description and safeArea at the top for IOS

- README.md
- UI/PetAdoptUI/PetAdoptUI/PetAdoptUI.Shared/MainPage.xaml
> fix: pet adopt image on IOS, and description

- UI/SkottieSample/SkottieSample/SkottieSample.Shared/MainPage.xaml.cs
> fix: can deploy on windows

- UI/StatusBarThemeColor/StatusBarColorSample.Shared/App.xaml.cs
> fix: android initially has the wrong statusbar color

- UI/MvuxHowTos/EditablePeopleApp/EditablePeopleApp/EditablePeopleApp.csproj
- UI/MvuxHowTos/EditablePeopleApp/EditablePeopleApp/MainPage.xaml
- UI/MvuxHowTos/MessagingPeopleApp/Directory.Packages.props
- UI/MvuxHowTos/MessagingPeopleApp/MessagingPeopleApp/MainPage.xaml
- UI/MvuxHowTos/MessagingPeopleApp/MessagingPeopleApp/MessagingPeopleApp.csproj
- UI/MvuxHowTos/PaginationPeopleApp/PaginationPeopleApp/MainPage.xaml
- UI/MvuxHowTos/PaginationPeopleApp/PaginationPeopleApp/PaginationPeopleApp.csproj
- UI/MvuxHowTos/PeopleApp/PeopleApp/MainPage.xaml
- UI/MvuxHowTos/PeopleApp/PeopleApp/PeopleApp.csproj
- UI/MvuxHowTos/SelectionPeopleApp/SelectionPeopleApp/MainPage.xaml
- UI/MvuxHowTos/SelectionPeopleApp/SelectionPeopleApp/SelectionPeopleApp.csproj
- UI/MvuxHowTos/StockMarketApp/StockMarketApp/MainPage.xaml
- UI/MvuxHowTos/StockMarketApp/StockMarketApp/StockMarketApp.csproj
- UI/MvuxHowTos/WeatherApp/WeatherApp/MainPage.xaml
- UI/MvuxHowTos/WeatherApp/WeatherApp/WeatherApp.csproj
- UI/MvuxHowTos/WeddingHallApp/WeddingHallApp/MainPage.xaml
- UI/MvuxHowTos/WeddingHallApp/WeddingHallApp/WeddingHallApp.csproj
closes #492 
- Adds a SafeArea (top & bottom) to each sample.
- TextWrapping added on ListView headers in PaginationPeopleApp.
> fix: MvuxHowTos apps layout

- README.md
- UI/UnoCupertinoSample/UnoCupertinoSample.Shared/MainPage.xaml
- UI/UnoCupertinoSample/UnoCupertinoSample.Shared/MainPage.xaml.cs
> fix: combobox itemsource

- README.md
- UI/UnoGoodReads/UnoGoodReads/UnoGoodReads.Shared/MainPage.xaml
> unogoodread description and small fix

- UI/XamlBasics/ListViewSample/ListViewSample.Shared/MainPage.xaml
- UI/XamlBasics/ListViewSample/ListViewSample.Windows/ListViewSample.Windows.csproj
> fix: UI for smaller devices for XamlBasics

- README.md
- UI/ToyCar/ToyCar.Shared/MainPage.xaml.cs
closes #517 
Added description to README.md for the TravelUI sample app.
> docs: added travelui description

- UI/TravelUI/TravelUI/MainPage.xaml
- UI/TravelUI/TravelUI/MainPage.xaml.cs
closes #518 
Modified assets links to be recognized on all platforms.
> fix: travelui assets

- README.md
- UI/UnoIslandsSampleApp/UnoIslandsSampleApp.Shared/MainPage.xaml.cs
> fix: added descripton to uno islands

- README.md
- UI/UnoMaterialToolkitSample/UnoMaterialToolkitSample/MainPage.xaml.cs
> feat: added UnoMaterialToolkitSample's description

- README.md
- UI/UnoMaterialSample/UnoMaterialSample/UnoMaterialSample/MainPage.xaml.cs
> fix: changed material documentation url

- README.md
ReadMe update:
Add .NET MAUI Embedding samples (ArcGis, DevExpress, GrapeCity, GrialKit, Syncfusion, Telerik)
> docs(ReadMe): Add .NET MAUI Embedding samples

- UI/MauiEmbedding/ArcGisApp/ArcGisApp.MauiControls/AppBuilderExtensions.cs
- UI/MauiEmbedding/ArcGisApp/ArcGisApp.MauiControls/EmbeddedControl.xaml.cs
Tidying up the map sample to use a simple map service instead of a floor manager
> chore: Tidyup up sample

- UI/MapControlSample/MapControlSample/MapControlSample.Shared/MainPage.xaml.cs
Things done:
1. Fixed Android (was missing currentPosition because no Mouse)
2. Resynchronize Zoom Level to Slider
> Fixing mapsui sample

- reference/SimpleCalc/MVU-X-CSharp/Directory.Packages.props
- reference/SimpleCalc/MVU-X-Xaml/Directory.Packages.props
- reference/SimpleCalc/MVVM-CSharp/Directory.Packages.props
- reference/SimpleCalc/MVVM-Xaml/Directory.Packages.props
Created from https://github.com/unoplatform/Uno.Samples/pull/591 and must only be merged after https://github.com/unoplatform/Uno.Samples/pull/591.
> chore: Updating Uno packages

- reference/SimpleCalc/MVU-X-CSharp/SimpleCalculator/SimpleCalculator.csproj
- reference/SimpleCalc/MVU-X-Xaml/SimpleCalculator/SimpleCalculator.csproj
- reference/SimpleCalc/MVVM-CSharp/SimpleCalculator/SimpleCalculator.csproj
- reference/SimpleCalc/MVVM-Xaml/SimpleCalculator/SimpleCalculator.csproj
- reference/SimpleCalc/README.md
Fixes: https://github.com/unoplatform/uno.samples-private/issues/126
> fix: Disabling source code updates

- reference/TubePlayer/Directory.Packages.props
- reference/TubePlayer/TubePlayer.Skia.Gtk/TubePlayer.Skia.Gtk.csproj
- reference/TubePlayer/TubePlayer.Wasm/TubePlayer.Wasm.csproj
Add Reference for the GTK works with the MediaPlayerElement + WASM reference
> chore: add gtk/wasm media player reference

- reference/TubePlayer/TubePlayer/Business/IYoutubeService.cs
- reference/TubePlayer/TubePlayer/Business/YoutubeService.cs
- reference/TubePlayer/TubePlayer/Business/YoutubeServiceMock.cs
- reference/TubePlayer/TubePlayer/Presentation/VideoDetailsModel.cs
This PR updates Tube Player Sample moving business logic out of the Model into the Service.
> chore: (Tube Player) move logic to service

- reference/TubePlayer/TubePlayer.Windows/TubePlayer.Windows.csproj
Fix for templates https://github.com/unoplatform/uno.templates/pull/494
Fix for SimpleCalc https://github.com/unoplatform/Uno.Samples/pull/619
> fix: Allow VS Code (with C# dev kit) to load TubePlayer solution

- reference/SimpleCalc/MVU-X-CSharp/Directory.Packages.props
- reference/SimpleCalc/MVU-X-Xaml/Directory.Packages.props
- reference/SimpleCalc/MVVM-CSharp/Directory.Packages.props
- reference/SimpleCalc/MVVM-Xaml/Directory.Packages.props
- reference/TubePlayer/Directory.Packages.props
Update uno fixing the layout trigger arrange phase multiple time
https://github.com/unoplatform/uno/issues/14373
> chore: update uno

- README.md
> feat: Added the SimpleCalc, Counter, TubePlayer and ToDo apps to the ReadME

- reference/Counter/CSharp-MVUX/Counter/MainModel.cs
- reference/Counter/CSharp-MVUX/Counter/MainPage.cs
- reference/Counter/CSharp-MVUX/Directory.Packages.props
- reference/Counter/XAML-MVUX/Counter/Countable.cs
- reference/Counter/XAML-MVUX/Counter/MainModel.cs
- reference/Counter/XAML-MVUX/Counter/MainPage.xaml
- reference/Counter/XAML-MVUX/Directory.Packages.props
Refactors Step and Count into an immutable record #https://github.com/unoplatform/private/issues/446
Updates Uno.Extensions.Reactive to 4.0.0 to be able to use UpdateAsync()
> chore: turn Step and Count into record

- UI/UnoBackgroundWorker/UnoBackgroundWorker/UnoBackgroundWorker/Presentation/MainPage.xaml.cs
Also needs correcting on [Blog: Background Work in Uno Platform Applications](https://platform.uno/blog/background-work-in-uno-platform-apps/)
A distraction found whilst trying to get a find a usable WASM threading solution 😵‍💫
> UnoBackgroundWorker sample - remove duplicate semicolon

- reference/Counter/CSharp-MVUX/.vscode/launch.json
- reference/Counter/CSharp-MVUX/.vscode/settings.json
- reference/Counter/CSharp-MVUX/.vscode/tasks.json
- reference/Counter/CSharp-MVVM/.vscode/launch.json
- reference/Counter/CSharp-MVVM/.vscode/settings.json
- reference/Counter/CSharp-MVVM/.vscode/tasks.json
- reference/Counter/XAML-MVUX/.vscode/launch.json
- reference/Counter/XAML-MVUX/.vscode/settings.json
- reference/Counter/XAML-MVUX/.vscode/tasks.json
- reference/Counter/XAML-MVVM/.vscode/launch.json
- reference/Counter/XAML-MVVM/.vscode/settings.json
- reference/Counter/XAML-MVVM/.vscode/tasks.json
- reference/SimpleCalc/CSharp-MVUX/.vscode/launch.json
- reference/SimpleCalc/CSharp-MVUX/.vscode/settings.json
- reference/SimpleCalc/CSharp-MVUX/.vscode/tasks.json
- reference/SimpleCalc/CSharp-MVVM/.vscode/launch.json
- reference/SimpleCalc/CSharp-MVVM/.vscode/settings.json
- reference/SimpleCalc/CSharp-MVVM/.vscode/tasks.json
- reference/SimpleCalc/XAML-MVUX/.vscode/launch.json
- reference/SimpleCalc/XAML-MVUX/.vscode/settings.json
- reference/SimpleCalc/XAML-MVUX/.vscode/tasks.json
- reference/SimpleCalc/XAML-MVVM/.vscode/launch.json
- reference/SimpleCalc/XAML-MVVM/.vscode/settings.json
- reference/SimpleCalc/XAML-MVVM/.vscode/tasks.json
- reference/TubePlayer/src/.vscode/launch.json
- reference/TubePlayer/src/.vscode/settings.json
- reference/TubePlayer/src/.vscode/tasks.json
Adds .vscode files with corresponding paths to Counter, SimpleCalc (SimpleCalculator) and TubePlayer single projects.
> chore: add vscode folders

- UI/MauiEmbedding/DevExpressApp/src/.vscode/launch.json
- UI/MauiEmbedding/DevExpressApp/src/.vscode/settings.json
- UI/MauiEmbedding/DevExpressApp/src/.vscode/tasks.json
> chore: added vscode folder

- UI/ChatSignalR/UnoChat.Client/UnoChat.Shared/ViewModel.cs
@jeromelaban I noticed that the #720 fix, and your suggested simplification had both been merged, creating a pointless nested if clause.
anyway, it should now be as desired 👍
> chore: improvement to wasm delay fix from #720

- reference/Counter/CSharp-MVUX/Directory.Build.props
- reference/Counter/CSharp-MVUX/global.json
- reference/Counter/CSharp-MVVM/Directory.Build.props
- reference/Counter/CSharp-MVVM/global.json
- reference/Counter/XAML-MVUX/Directory.Build.props
- reference/Counter/XAML-MVUX/global.json
- reference/Counter/XAML-MVVM/Directory.Build.props
- reference/Counter/XAML-MVVM/global.json
> [Counter App] chore: updating Uno Sdk

- reference/SimpleCalc/CSharp-MVUX/Directory.Build.props
- reference/SimpleCalc/CSharp-MVUX/global.json
- reference/SimpleCalc/CSharp-MVVM/Directory.Build.props
- reference/SimpleCalc/CSharp-MVVM/global.json
- reference/SimpleCalc/XAML-MVUX/Directory.Build.props
- reference/SimpleCalc/XAML-MVUX/global.json
- reference/SimpleCalc/XAML-MVVM/Directory.Build.props
- reference/SimpleCalc/XAML-MVVM/global.json
> [Simple Calc]  chore: updating Uno.SDK

- UI/WindowingSamples/src/Directory.Build.props
- UI/WindowingSamples/src/global.json
Addresses https://github.com/unoplatform/Uno.Samples/pull/680#issuecomment-2113694760
> fix: Bump windowing to improve x:Bind support

- UI/ScottPlot/QuickstartSample/Directory.Packages.props
- UI/ScottPlot/QuickstartSample/ScottPlotSample/ScottPlotSample.csproj
- UI/ScottPlot/SignalPlotFiveMillionPointsSample/Directory.Packages.props
- UI/ScottPlot/SignalPlotFiveMillionPointsSample/ScottPlotSample/ScottPlotSample.csproj
Following the work done for #821, updating ScottPlot samples with latest ScottPlot.WinUI version 5.0.38
> chore: Update ScottPlot samples with latest ScottPlot.WinUI version 5.0.38

- UI/MVUX/src/global.json
- doc/samples.md
Following https://github.com/unoplatform/Uno.Samples/pull/822
> chore: Update global.json to use the latest stable

- reference/ToDo/src/Directory.Build.props
Related issue: https://github.com/unoplatform/Uno.Samples/issues/828
- Update Directory.Build.props to remove unnecessary version override with Uno.Sdk 5.4 for ToDo sample
> chore(ToDo): Update Directory.Build.props to remove unnecessary version override with Uno.Sdk 5.4

- UI/ChatGPT/src/ChatGPT/ChatGPT.csproj
- UI/ChatGPT/src/Directory.Build.props
- UI/ChatGPT/src/global.json
> [ChatGPT App] chore: updating Uno Sdk

- UI/ChatGPT/src/ChatGPT/ChatGPT.csproj
- UI/MVUX/src/MVUX/MVUX.csproj
- reference/Commerce/src/Commerce/Commerce.csproj
- reference/Counter/CSharp-MVUX/Counter/Counter.csproj
- reference/Counter/CSharp-MVVM/Counter/Counter.csproj
- reference/Counter/XAML-MVUX/Counter/Counter.csproj
- reference/SimpleCalc/CSharp-MVUX/SimpleCalculator/SimpleCalculator.csproj
- reference/SimpleCalc/CSharp-MVVM/SimpleCalculator/SimpleCalculator.csproj
- reference/SimpleCalc/XAML-MVUX/SimpleCalculator/SimpleCalculator.csproj
- reference/SimpleCalc/XAML-MVVM/SimpleCalculator/SimpleCalculator.csproj
- reference/ToDo/src/ToDo/ToDo.csproj
- reference/TubePlayer/src/TubePlayer/TubePlayer.csproj
Related item: https://github.com/unoplatform/Uno.Samples/issues/828
> chore: Add more details for 5.4 migration regarding temporary adjustment of WindowsSdkPackageVersion

- UI/ChatUI/src/ChatUI/App.xaml
- UI/ChatUI/src/ChatUI/App.xaml.cs
- UI/ChatUI/src/ChatUI/Behaviors/CommandOnKeyPressBehavior.cs
- UI/ChatUI/src/ChatUI/Behaviors/ReversedPointerWheel.cs
- UI/ChatUI/src/ChatUI/ChatUI.csproj
- UI/ChatUI/src/ChatUI/Commands/RelayCommand.cs
- UI/ChatUI/src/ChatUI/MainPage.xaml
- UI/ChatUI/src/ChatUI/MainPage.xaml.cs
- UI/ChatUI/src/ChatUI/Models/MessageModel.cs
- UI/ChatUI/src/ChatUI/Presentation/MessageTemplateSelector.cs
- UI/ChatUI/src/ChatUI/Services/IMessageService.cs
- UI/ChatUI/src/ChatUI/Services/MessageService.cs
- UI/ChatUI/src/ChatUI/Styles/AppResources.xaml
- UI/ChatUI/src/global.json
- doc/samples.md
Issue: #828 
- Update Sdk to 5.4.5
- Some files are using tab and others space for indentation. Changes for all to use space.
- Clean unused usings
- Fix a bug where the message text wouldn't appear if enter was hit to send
- Add ChatUI to doc\samples.md
> chore: Update ChatUI to Uno.Sdk 5.4

- UI/PongWars/src/Directory.Build.props
- UI/PongWars/src/UnoPongWars/UnoPongWars.csproj
- UI/PongWars/src/global.json
> [PongWars App] chore: updating SDK

- UI/Benchmark/AppBenchmark/AppBenchmark/App.xaml
- UI/Benchmark/AppBenchmark/AppBenchmark/App.xaml.cs
- UI/Benchmark/AppBenchmark/AppBenchmark/AppBenchmark.csproj
- UI/Benchmark/AppBenchmark/AppBenchmark/BenchmarkDotNetControl.xaml
- UI/Benchmark/AppBenchmark/AppBenchmark/Benchmarks/FinalizerBenchmark.cs
- UI/Benchmark/AppBenchmark/AppBenchmark/Benchmarks/GCHandleBenchmark.cs
- UI/Benchmark/AppBenchmark/AppBenchmark/Benchmarks/SpanBenchmark.cs
- UI/Benchmark/AppBenchmark/AppBenchmark/Benchmarks/TryFinallyBenchmark.cs
- UI/Benchmark/AppBenchmark/AppBenchmark/MainPage.xaml
- UI/Benchmark/AppBenchmark/AppBenchmark/Properties/launchSettings.json
- UI/Benchmark/AppBenchmark/global.json
Issue: https://github.com/unoplatform/Uno.Samples/issues/828
- Update Sdk to 5.4.5
- Some files were using tab and others space for indentation. Changes for all to use space.
- Clean unused usings
- Removed unused platform from launchSettings.json
> chore: Update Benchmark to Uno.Sdk 5.4

- UI/ScottPlot/DataPersistedSample/global.json
- UI/ScottPlot/QuickstartSample/Directory.Packages.props
- UI/ScottPlot/QuickstartSample/global.json
- UI/ScottPlot/README.md
- UI/ScottPlot/SignalPlotFiveMillionPointsSample/Directory.Packages.props
- UI/ScottPlot/SignalPlotFiveMillionPointsSample/global.json
Update ScottPlot samples to latest **Uno.Sdk 5.4.8** and to latest **ScottPlot.WinUI 5.0.39**
> chore: Update ScottPlot samples to latest Uno.Sdk 5.4.8 and to latest ScottPlot.WinUI 5.0.39

- UI/CardViewMigration/CardViewMigration/CardViewMigration/App.xaml.cs
- UI/CardViewMigration/CardViewMigration/CardViewMigration/CardViewCodePage.cs
- UI/CardViewMigration/CardViewMigration/CardViewMigration/CardViewCodePage.xaml
- UI/CardViewMigration/CardViewMigration/CardViewMigration/CardViewMigration.csproj
- UI/CardViewMigration/CardViewMigration/CardViewMigration/CardViewXamlPage.xaml
- UI/CardViewMigration/CardViewMigration/CardViewMigration/CardViewXamlPage.xaml.cs
- UI/CardViewMigration/CardViewMigration/CardViewMigration/ControlTemplatePage.xaml
- UI/CardViewMigration/CardViewMigration/CardViewMigration/ControlTemplatePage.xaml.cs
- UI/CardViewMigration/CardViewMigration/CardViewMigration/Controls/CardView.xaml
- UI/CardViewMigration/CardViewMigration/CardViewMigration/MainPage.xaml
- UI/CardViewMigration/CardViewMigration/Directory.Packages.props
- UI/CardViewMigration/CardViewMigration/global.json
- UI/CardViewMigration/README.md
Issue: https://github.com/unoplatform/Uno.Samples/issues/828
- Update Sdk to 5.4.8
- Removed unusded usings
- Fixed indentation
> chore: Update CardView to Uno.Sdk 5.4

- build/templates/dotnet-install-windows.yml
- reference/Counter/CSharp-MVUX/.vscode/launch.json
- reference/Counter/CSharp-MVUX/.vscode/tasks.json
- reference/Counter/CSharp-MVUX/Counter/App.xaml.cs
- reference/Counter/CSharp-MVUX/Counter/Counter.csproj
- reference/Counter/CSharp-MVUX/Counter/Properties/launchSettings.json
- reference/Counter/CSharp-MVUX/Directory.Packages.props
- reference/Counter/CSharp-MVUX/global.json
- reference/Counter/CSharp-MVVM/.vscode/launch.json
- reference/Counter/CSharp-MVVM/.vscode/tasks.json
- reference/Counter/CSharp-MVVM/Counter/App.xaml.cs
- reference/Counter/CSharp-MVVM/Counter/Counter.csproj
- reference/Counter/CSharp-MVVM/Counter/Properties/launchSettings.json
- reference/Counter/CSharp-MVVM/Directory.Packages.props
- reference/Counter/CSharp-MVVM/global.json
- reference/Counter/XAML-MVUX/.vscode/launch.json
- reference/Counter/XAML-MVUX/.vscode/tasks.json
- reference/Counter/XAML-MVUX/Counter/App.xaml.cs
- reference/Counter/XAML-MVUX/Counter/Counter.csproj
- reference/Counter/XAML-MVUX/Counter/Properties/launchSettings.json
- reference/Counter/XAML-MVUX/Directory.Packages.props
- reference/Counter/XAML-MVUX/global.json
- reference/Counter/XAML-MVVM/.vscode/launch.json
- reference/Counter/XAML-MVVM/.vscode/tasks.json
- reference/Counter/XAML-MVVM/Counter/App.xaml.cs
- reference/Counter/XAML-MVVM/Counter/Counter.csproj
- reference/Counter/XAML-MVVM/Counter/Properties/launchSettings.json
- reference/Counter/XAML-MVVM/Directory.Packages.props
- reference/Counter/XAML-MVVM/global.json
Upgrade Counter samples to latest **Uno.Sdk 5.6.22** and **NET 9**
Related issue: https://github.com/unoplatform/Uno.Samples/issues/862
> Upgrade Counter samples to latest Uno.Sdk 5.6.22 and NET 9

- reference/Commerce/src/global.json
- reference/Counter/CSharp-MVUX/global.json
- reference/Counter/CSharp-MVVM/global.json
- reference/Counter/XAML-MVUX/global.json
- reference/Counter/XAML-MVVM/global.json
- reference/SimpleCalc/CSharp-MVUX/global.json
- reference/SimpleCalc/CSharp-MVVM/global.json
- reference/SimpleCalc/XAML-MVUX/global.json
- reference/SimpleCalc/XAML-MVVM/global.json
- reference/ToDo/src/global.json
- reference/TubePlayer/src/global.json
Related Issue: https://github.com/unoplatform/Uno.Samples/issues/862
> chore: Update reference samples to latest uno.sdk 5.6 service release

- reference/Commerce/src/global.json
- reference/Counter/CSharp-MVUX/global.json
- reference/Counter/CSharp-MVVM/global.json
- reference/Counter/XAML-MVUX/global.json
- reference/Counter/XAML-MVVM/global.json
- reference/SimpleCalc/CSharp-MVUX/global.json
- reference/SimpleCalc/CSharp-MVVM/global.json
- reference/SimpleCalc/XAML-MVUX/global.json
- reference/SimpleCalc/XAML-MVVM/global.json
- reference/ToDo/src/global.json
- reference/TubePlayer/src/global.json
Related issue: https://github.com/unoplatform/Uno.Samples/issues/862
Update reference samples to latest Uno.Sdk 5.6.45
> chore: Update reference samples to latest Uno.Sdk 5.6.45

- doc/samples.md
Related issue https://github.com/unoplatform/private/issues/743
> docs: Add chefs reference

- UI/SKCanvasElementShowcase/SKCanvasElementShowcase/SKCanvasElementImpl.skia.cs
closes https://github.com/unoplatform/uno/issues/20345
> fix(skcanvaselementshowcase): invalidate when sample changes

- doc/samples.md
changed the order of sample apps
> docs: Update samples.md
