- UI/TheCatApiClient/TheCatApiClient/TheCatApiClient.Shared/Models/ViewModels/DispatchedBindableBase.cs
@ebariche During the review of the associated tutorial, a change to how thread access is handled when running under WASM was recommended by @davidjohnoliver .
> chore: update TheCatApiClient sample for WASM thread dispatch

- UI/ChatSignalR/UnoChat.Service/Startup.cs
Change to use UseCors step earlier in UnoChat.Service configuration so it works when launched locally.
Based on: https://stackoverflow.com/a/60469784
Was not working for me when I launched the service locally. Currently this uses an azure website as a chat hub which hides this issue. https://github.com/unoplatform/Uno.Samples/blob/5564c8f56dd41681e6b9213aa197de28a07bcee3/UI/ChatSignalR/UnoChat.Client/UnoChat.Client.Shared/ViewModel.cs#L71
When reverting to use localhost the problem appears.
> Fix CORS error when launching UnoChat.Service locally.

- UI/UnoContoso/UnoContoso.Service/Properties/launchSettings.json
- UI/UnoContoso/UnoContoso.Shared/App.xaml.cs
closes #127 
Ports from WASM and Services projects were the same if using Kestrel.
> fix: adjusting ports to avoid conflict

- UI/SkiaSharpTest/SkiaSharpTest/SkiaSharpTest.Shared/MainPage.xaml
- UI/SkiaSharpTest/SkiaSharpTest/SkiaSharpTest.Shared/MainPage.xaml.cs
- UI/SkiaSharpTest/SkiaSharpTest/SkiaSharpTest.UWP/SkiaSharpTest.UWP.csproj
WMC1121: Invalid binding assignment : Events can only be bound to non-overloaded methods
> fix: Adjust SkiaSharp template for x:Bind error

- .vsts-ci.yml
Trailing brace is causing error in build
see https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=60730&view=logs&j=b0e9e703-bc7b-5b6a-2ec3-61742e5311eb&t=e4987f70-9797-5667-3e14-6d3b01ce7da1&l=286
> fix: Remove extra brace

- reference/Commerce/Commerce/Commerce/Presentation/LoginViewModel.cs
Running the application, the login page (LoginPage) appears, but no viewmodel il bound to the view.
Make LoginViewModel public, so that it can be injected and bound to the LoginPage
> Fix: Make LoginViewModel public

- reference/Commerce/Commerce/Commerce/Commerce.csproj
- reference/Commerce/Commerce/Commerce/Data/ProductEndpoint.cs
This PR ensures 'products.json' and 'reviews.json' are copied to the output directory at runtime, resolving a file access issue that made the pages empty.
#415
> fix: empty pages

- UI/Benchmark/AppBenchmark/AppBenchmark.Mobile/AppBenchmark.Mobile.csproj
- UI/Benchmark/AppBenchmark/AppBenchmark.Shared/MainPage.xaml
- UI/Benchmark/AppBenchmark/AppBenchmark.Wasm/AppBenchmark.Wasm.csproj
- UI/Benchmark/AppBenchmark/AppBenchmark.Windows/AppBenchmark.Windows.csproj
closes #443 
Added SafeArea to the top & bottom of the Benchmark's sample main page.
> fix: add spacing at top of Benchmark sample

- UI/MigratingEffects/UnoEffectsSample/UnoEffectsSample/MainPage.xaml
closes #467 
The resource key BackgroundBrush was not found on the MainPage. Replaced it with the ApplicationPageBackgroundThemeBrush.
> fix: changed windows background brush for migratingeffects sample

- UI/AutoSuggestSample/AutoSuggestSample/AutoSuggestSample.Shared/MainPage.xaml
closes #441 
Adding TextWrapping and changing Margins on the main page of the AutoSuggestLayout.
> fix: autosuggest layout on Mobile

- UI/TheCatApiClient/TheCatApiClient/TheCatApiClient.Shared/MainPage.xaml
closes #512 
Title text and description text is no longer truncated on Mobile (added wrapping).
> fix: CatApiClient mobile layout

- UI/MvuxHowTos/SliderApp/SliderApp/MainPage.xaml
closes #496 
Added Slider content back to the sample app. Disregard this PR if we do not want this slider anymore. (took it from this commit: https://github.com/unoplatform/Uno.Samples/commit/fbfddcce5169a3e577913e32f6cbe655899472b6#diff-2c972e423ada7e5655973a8f3761a0949a302309026b1699c5fa2ae6eef42de5)
> fix: added slider content back

- UI/XamlBrewerUnoApp/XamlBrewerUnoApp/XamlBrewerUnoApp/Shell.xaml.cs
- build-samples.yml
This flag makes `LinkAssembliesNoShrink` run a lot faster. It takes it down from 9 minutes to 3 seconds!
> ci: Try to skip keep alives

- reference/TubePlayer/TubePlayer/appsettings.development.json
The API Key that was there has surely already been scraped by bots and harvested for all its requests as I am just seeing the Error state now if I run this app as is. We should leave this as a placeholder
> chore: remove api key

- reference/SimpleCalc/MVU-X-CSharp/SimpleCalculator.Windows/SimpleCalculator.Windows.csproj
- reference/SimpleCalc/MVU-X-Xaml/SimpleCalculator.Windows/SimpleCalculator.Windows.csproj
- reference/SimpleCalc/MVVM-CSharp/SimpleCalculator.Windows/SimpleCalculator.Windows.csproj
- reference/SimpleCalc/MVVM-Xaml/SimpleCalculator.Windows/SimpleCalculator.Windows.csproj
Fix for templates https://github.com/unoplatform/uno.templates/pull/494
> fix: Allow VS Code (with C# dev kit) to load SimpleCalculator solution

- reference/SimpleCalc/MVU-X-CSharp/.vscode/extensions.json
- reference/SimpleCalc/MVU-X-Xaml/.vscode/extensions.json
- reference/SimpleCalc/MVVM-CSharp/.vscode/extensions.json
- reference/SimpleCalc/MVVM-Xaml/.vscode/extensions.json
This way VS Code will suggest to install the Uno Platform extension (if not already present) and its dependencies.
> feat: Add extensions.json to SimpleCalc solutions

- UI/PhotoViewer/InteractionControls/ZoomContentControl.cs
- UI/PhotoViewer/InteractionControls/ZoomContentControl.xaml
Fixes #651 
ScrollBars were not accepting inverted values, so we had to handle that.
Also, TemplateBinding doesn't allow TwoWay mode, leading to change the values when scrolling the bars.
> Fix ScrollBars behavior

- UI/ChatSignalR/UnoChat.Client/UnoChat.Shared/ViewModel.cs
rectified an issue with `Delay` which would cause a permanent hang in Web Assembly.  
perhaps a temporary fix, until `threading` in .NET 9, as alluded to by @jeromelaban [here](https://github.com/unoplatform/uno/issues/13370)  
for the ChatSignalR sample:
- closes #417 
- closes #430 
- *should be the fix that* closes #118 
- no connection issues once fixed.. the observed issue was likely the hang
- the only connection changes I have ever had to make are to change the WASM port from 5000 to 5001- likely no relation
> fix: ChatSignalR - stop hang on WASM

- .gitattributes
change should make `TSQL` disappear as the main type of this repo:
`C#` should then show, as the second largest portion, by type.
**Please note:** may take a few minutes post-merge for the repo to show as `C#`
> Show repository as mainly C# and not TSQL

- reference/ToDo/src/ToDo/Views/Dialogs/SettingsFlyout.xaml
Fix Wide layout and content for Narrow to avoid exceptions on Windows for Settings Flyout
| Wide - BEFORE | Wide - AFTER |
|--------|--------|
|  ![wide-before](https://github.com/unoplatform/Uno.Samples/assets/16295702/3da7a483-188f-4d62-962c-39e4245fcd10) |  ![wide-after](https://github.com/unoplatform/Uno.Samples/assets/16295702/e148e822-e632-4a2f-b89f-ee39b0336a83) |
> fix(Settings): Wide layout and content for Narrow to avoid exceptions on Windows

- UI/WindowsCommunityToolkit/README.md
Following the changes for https://github.com/unoplatform/uno/pull/17374, adding additional details for non-Windows platform compatibility for the samples documentation.
> docs(WCT): Add additional details for non-Windows platform compatibility for the samples documentation

- UI/PhotoViewer/PhotoViewer/AppResources.xaml
The `ZoomContentControl` is currently not working as reported https://github.com/unoplatform/uno.toolkit.ui/issues/1109#issuecomment-2223150212. The PhotoViewer was missing the import of the necessary styles, so the IsAllowedToWork returned false even when the switch should have enabled it.
> fix: `ZoomContentControl` in PhotoViewer not working

- UI/ScottPlot/QuickstartSample/global.json
- UI/ScottPlot/SignalPlotFiveMillionPointsSample/global.json
Update ScottPlot samples to latest Uno.Sdk 5.3.108
Tested on all platforms
> chore: Update ScottPlot samples to latest Uno.Sdk 5.3.108

- reference/Counter/CSharp-MVUX/Counter/Counter.csproj
- reference/Counter/CSharp-MVUX/Counter/GlobalUsings.cs
- reference/Counter/CSharp-MVUX/Counter/MainPage.cs
- reference/Counter/CSharp-MVUX/global.json
- reference/Counter/XAML-MVUX/Counter/Counter.csproj
- reference/Counter/XAML-MVUX/Counter/GlobalUsings.cs
- reference/Counter/XAML-MVUX/Counter/MainPage.xaml
- reference/Counter/XAML-MVUX/global.json
- reference/SimpleCalc/CSharp-MVUX/SimpleCalculator/GlobalUsings.cs
- reference/SimpleCalc/CSharp-MVUX/SimpleCalculator/MainPage.cs
- reference/SimpleCalc/CSharp-MVUX/SimpleCalculator/SimpleCalculator.csproj
- reference/SimpleCalc/CSharp-MVUX/global.json
- reference/SimpleCalc/XAML-MVUX/SimpleCalculator/GlobalUsings.cs
- reference/SimpleCalc/XAML-MVUX/SimpleCalculator/MainPage.xaml.cs
- reference/SimpleCalc/XAML-MVUX/SimpleCalculator/SimpleCalculator.csproj
- reference/SimpleCalc/XAML-MVUX/global.json
- reference/TubePlayer/src/Directory.Build.props
- reference/TubePlayer/src/TubePlayer/GlobalUsings.cs
- reference/TubePlayer/src/TubePlayer/Presentation/MainPage.cs
- reference/TubePlayer/src/TubePlayer/Presentation/VideoDetailsPage.cs
- reference/TubePlayer/src/TubePlayer/TubePlayer.csproj
- reference/TubePlayer/src/global.json
https://github.com/unoplatform/uno.extensions-private/issues/208
> chore: update samples for MVUX generated class

- doc/samples.md
Related issue: https://github.com/unoplatform/Uno.Samples/issues/828
- Add source link for Media Gallery sample
> docs: Add source link for Media Gallery sample

- reference/Commerce/src/Directory.Build.props
Related issue: https://github.com/unoplatform/Uno.Samples/issues/828
- Update Directory.Build.props to remove unnecessary version override with Uno.Sdk 5.4 for Commerce Sample
> chore(Commerce): Update Directory.Build.props to remove unnecessary version override with Uno.Sdk 5.4

- UI/Navigation/src/Directory.Build.props
- UI/Navigation/src/Navigation/Navigation.csproj
- UI/Navigation/src/global.json
Related issue: https://github.com/unoplatform/Uno.Samples/issues/828
- Update Directory.Build.props to remove unnecessary version override with Uno.Sdk 5.4 for Navigation sample
> chore(Navigation): Update Directory.Build.props to remove unnecessary version override with Uno.Sdk 5.4

- UI/Navigation/src/Navigation/App.xaml.cs
- UI/Navigation/src/Navigation/Navigation.csproj
- UI/Navigation/src/Navigation/Presentation/MainPage.xaml
- UI/Navigation/src/Navigation/Presentation/ToFromQuery/ToFromQueryMainPage.xaml
- UI/Navigation/src/Navigation/Presentation/ToFromQuery/ToFromQueryMainPage.xaml.cs
- UI/Navigation/src/Navigation/Presentation/ToFromQuery/ToFromQueryMainViewModel.cs
- UI/Navigation/src/global.json
Closes #859
---
Changes include:
- update uno.sdk to latest
- ~remove workaround for WindowsSdkPackageVersion~
- adjust sample to properly navigate using To/FromQuery without static string
> chore: Adjust nav sample to properly navigate with to from query
